version: "3"
services:
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --production --legacy-peer-deps && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on:
      - mongo
    networks:
      - clean-node-api
    links:
      - mongo
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - clean-node-api
networks:
  clean-node-api:
    driver: bridge

volumes:
  mongodb:
    driver: local
